### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rosch100** [coppit/docker-inotify-command#4]
Thanks for the implementation!

I have a suggestion to make your container useful also for non-linux file systems (e.g. mounted smb shares).

The python watchdog also supports PollingObserver, which can detect changes in other file systems. If changing "Observer" to "PollingObserver", then your solution also works for these file systems.

It would be great to make it configurable e.g. via environment.

**Comment by coppit** [comment]
Implemented. Thanks for the feature suggestion!

There's a timeout option that defaults to 1 second. It seems to run quickly without timing out, but I might need to increase that number, or make it configurable.

Making this feature configurable in the environment doesn't really work, since each directory being monitoring might need a different policy. (When people use multiple config files.)
